### ISSUE TITLE
XLButtonBarPagerTabStripViewController on swift

### ISSUE THREAD

**Issue by tiagopigatto** [xmartlabs/XLPagerTabStrip#102]
Whenever I try to implement ButtonBarPagerStrip I dont see the buttons on top of the screen, is that a known issue?

**Comment by tiagopigatto** [comment]
Actually the buttonBarView gets overlapped by the navigationController, how can I put the buttonBarView automatically below the navigationBar?

**Comment by mtnbarreto** [comment]
@tiagopigatto you can do it using storyboard.

1. Add a collection view and set up its class to XLButtonBarView. 
2. connect buttonBarView outlet: `@property (nonatomic) IBOutlet XLButtonBarView * buttonBarView;`
3. Set up constraints. 

Regards

**Comment by tiagopigatto** [comment]
I a checking the demo code for a while and I don't see where in the code you connect the buttonBarView outlet and how you do that. I can see that the outlet is connected, but I am getting a little bit confused here.

**Comment by mtnbarreto** [comment]
Search for `customBarView` in your code because XLPagerTabStrip doesn't have this symbol.

-----------------------------------------------

You can connect the outlet by selecting the `XLButtonBarPagerTabStripViewController` controller from the storyboard and then view the connector inspector as the image below illustrates.


![screen shot 2016-01-13 at 1 33 01 pm](https://cloud.githubusercontent.com/assets/1746532/12300766/b41276ee-b9fb-11e5-8f23-1556a908ea15.png)

you should see a buttonBarView outlet and also a containerView.

Hope it helps!

**Comment by tiagopigatto** [comment]
Even after connecting the outlets as you said, I am still getting this error:

**"ContainerViewController 0x7fdd9be36f60> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key customBarView."**

**Comment by mtnbarreto** [comment]
You can see here that the library doesn't have any `customBarView`. 
https://github.com/xmartlabs/XLPagerTabStrip/search?utf8=%E2%9C%93&q=customBarView

**Comment by tiagopigatto** [comment]
I actually had a view beneath the containerView named customBarView and couldn't see it because the background was white. Anyways, everything works great now. Thanks very much for your help and patience!

**Comment by mtnbarreto** [comment]
@tiagopigatto great! you welcome!

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
