### ISSUE TITLE
How to use only code ,without xib and storyboard!

### ISSUE THREAD

**Issue by heichong** [xmartlabs/XLPagerTabStrip#114]
has any demo? thanks very much

**Comment by mtnbarreto** [comment]
@heichong Sorry but we don't have any demo because is not the recommended approach to use the library since it's quite hard to set up views position properly.

Anyway, if you still want to set up the views programmatically, depending on the pager type, you may have to set up views frame after call super.viewDidLoad or viewWillAppear from your pager view controller.

Regards

**Comment by heichong** [comment]
@mtnbarreto  thanks for reply
