### ISSUE TITLE
objective-c support?

### ISSUE THREAD

**Issue by gudjao** [xmartlabs/XLPagerTabStrip#117]
Will this support objective-c?

**Comment by mtnbarreto** [comment]
@gudjao  You can use version 4.0.0 from objective-c base code by importing it as a framework (ios 8 and up required)
Additionally any class that extend from a pager controller must be written in swift since Objective-C is not able to translate certain features that are specific to Swift.

For more information see: [Using Swift with Cocoa and Objective-C](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/index.html#//apple_ref/doc/uid/TP40014216-CH2-ID0)

-------------------------------------------------

**Obj-c Branch**
We have this branch that basically is the same swift library but written in objective-c (this is the code  before we started to port the library to swift): https://github.com/xmartlabs/XLPagerTabStrip/tree/obj-c .if you are able to use XLPagerTabStrip swift version prefer it over objective-c since we will no longer provide support for obj-c version.

**Comment by gudjao** [comment]
Ok Thanks.

**Comment by JyothirmaiRachuri** [comment]
Does objective c support XLPageTabStrip . I am working on xcode 9.
