### ISSUE TITLE
Tab bar to bottom

### ISSUE THREAD

**Issue by viveksinha9** [xmartlabs/XLPagerTabStrip#163]
Is there anyway to show tabbar at bottom instead of top?

**Comment by vfedasyuk** [comment]
`var frame = buttonBarView.frame
        frame.origin.y = view.frame.height - frame.height
        buttonBarView.frame = frame
        
        var containterFrame = containerView.frame
        containterFrame.origin.y = 0
        containerView.frame = containterFrame`


does a trick for me

**Comment by robcecil** [comment]
@vfedasyuk, where?

**Comment by fedeojeda95** [comment]
Hi @viveksinha9 

There is a way, yes. 

If you are using interface builder, and you are setting the `buttonBarView` and `containerView` outlets from the storyboard, the only thing needed would be to add the necessary constraints so that the UICollectionView that represents the `buttonBarView` is at the bottom, and add constraints to the UIScrollView that represent the `containerView` so that it stays at top.

If you are creating everything programmatically, the way that @vfedasyuk mentioned would work. By changing the `buttonBarView` frame to the bottom and the `containerView` frame to the top would work. 

Hope it helps! Regards,

**Comment by tarek903** [comment]
@vfedasyuk where to put this code ,  thanks

**Comment by grizzly** [comment]
Using your method (code) works. But only on swiping. Taping on one entry lets jump the contentView to the top, so the content is behind the status bar ...

**Comment by Albinzr** [comment]
Is there any way to do this?
