### ISSUE TITLE
about Nav button style add another button

### ISSUE THREAD

**Issue by songxing10000** [xmartlabs/XLPagerTabStrip#170]
so strange,the picture cann'nt upload.  I mean how to add a button at the right and left position on nav button style demo ,just like the position of the  navigationBar leftBarItem or rightBarItem

**Comment by santiagofm** [comment]
You definitely can achieve this. Instead of adding the `ButtonBarView` as subview of the `navigationBar` as in the NavBar Example, you can set it as the `navigationItem`'s `titleView` and just add right/left `BarButtonItem`s as you normally would.

```swift
override func viewDidLoad() {
    // set up style before super view did load is executed
    settings.style.buttonBarBackgroundColor = .clear
    settings.style.selectedBarBackgroundColor = .orange
    //-
    super.viewDidLoad()
        
    buttonBarView.removeFromSuperview()
    navigationItem.titleView = buttonBarView
        
    let rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: nil)
    navigationItem.rightBarButtonItem = rightBarButtonItem
        
    let leftBarbuttonItem = UIBarButtonItem(barButtonSystemItem: .cancel, target: self, action: nil)
    navigationItem.leftBarButtonItem = leftBarbuttonItem

    ...

}
```

![image](https://cloud.githubusercontent.com/assets/6749415/26166233/384af078-3b09-11e7-866f-fb043d867826.png)

Cheers
