### ISSUE TITLE
Adding Bar Button just in one ViewController. 

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/XLPagerTabStrip#199]
Using Version 7.3.1 (7D1014)
I am implementing the TwitterPagerTabStrip.

How can I add a button only in one view controller? I want to add a rightBarButtonItem only in the child_6 which is the "NeuromusculoskeletalTableViewController". (Screenshot below). Right now, the rightBarButtonItem is visible in every view controller. but I only want to show it in the last view controller. 

Any ideas on how can I implement this?

Here is a screenshot of the code I have right now:

<img width="619" alt="screenshot 2016-08-02 10 29 45" src="https://cloud.githubusercontent.com/assets/6026875/17336586/10b1460c-589c-11e6-9e1c-0b57b7f78ab9.png">

**Comment by DylanModesitt** [comment]
You could imbed that child in its own navigation controller. If that doesn't work for you then you can programmatically add the barButtonItem and remove it when the other views appear.

**Comment by JorgeAGomez** [comment]
When I add the barButtonItem programmatically in any of the tableViewControllers it doesn't not appear when I run the app.

**Comment by santiagofm** [comment]
Hey @JorgeAGomez ! It's been a long time but you should be adding the `BarButtonItem` in the parent `UIViewController`(i.e the one that shows in the image) because thats the one embedded in a `UINavigationViewController`. The you should show/hide when the child viewcontroller changes depending on what you want.

Cheers
