### ISSUE TITLE
How to remove gap between button bar view and container view?

### ISSUE THREAD

**Issue by chiayo2142** [xmartlabs/XLPagerTabStrip#200]
Hello everyone. I founded the problem when I implement ButtonBarPagerTabStripViewController. I founded gap between button bar view and scroll view (container view) because I embed navigation bar to the view but when I remove navigation bar it's display perfectly. How does I solve it?

![gap-problem](https://cloud.githubusercontent.com/assets/5765690/17362939/ced0808e-59a1-11e6-9d23-960772173589.jpg)

**Comment by DylanModesitt** [comment]
Try going to your `UIScrollView` that is set as your `containerView` and disabling scrolling in the scoreboard. (this will not disable scrolling on the `tableView`)

![screen shot 2016-08-03 at 6 11 25 pm](https://cloud.githubusercontent.com/assets/8339189/17387136/bb4cb984-59a5-11e6-9aca-b3d19ea3e3f0.png)

**Comment by chiayo2142** [comment]
@DylanModesitt  Thank you for you helped. It's can remove gap but it's can't change to next when I try to swipe its.

**Comment by Urkman** [comment]
Disable "Adjust Scroll View Insets" works for me...

**Comment by omartio** [comment]
@Urkman Thank you! It works

**Comment by chiayo2142** [comment]
Thank you everyone

**Comment by stillwalk** [comment]
@Urkman when I set *self.automaticallyAdjustsScrollViewInsets = false* to ManagerViewController(who inherit from ButtonBarPagerTabStripViewController）, [containerView.contentOffset.y range from 0 to -20.0--#190](https://github.com/xmartlabs/XLPagerTabStrip/issues/190),  
do you have the same problem?

**Comment by fedeojeda95** [comment]
Hi! If you have any more problems with this, please check #290 to see the discussion and possible solutions. Cheers

**Comment by qu4sar** [comment]
Same problem, can you help me ? I've disabled "Adjust Scroll View Insets" into the viewDidLoad() on my "Container" Controller. The child controllers are only UIViewController with a UITableView inner of this.

**Comment by stillwalk** [comment]
@qu4sar I'm not. I using other library now.

**Comment by qu4sar** [comment]
@stillwalk  Wonderful! :(  What library?

**Comment by stillwalk** [comment]
@qu4sar [VTMagic](https://github.com/tianzhuo112/VTMagic)

**Comment by marcustoy** [comment]
I added this code under the the UIViewController class that controls the child VC (a subclass of ButtonBarPagerTabStripViewController), and it is solved the issue for me:

`override public var scrollPercentage: CGFloat {
        containerView.contentOffset.y = -20.0
        return super.scrollPercentage
}`


Hope it helps!

**Comment by abesmon** [comment]
It's good to mention, that you should disable "Adjust Scroll View Insets" on StripViewController not on its embed viewControllers. That wasnt clear to me, so maybe it helps someone

**Comment by novalagung** [comment]
In case anyone still got this issue. I managed to solve by disabling "Adjust Scroll View Insets" on the **INITIAL VIEW CONTROLLER**. Initial controller is not always the one that inherit `ButtonBarPagerTabStripViewController`. Really depend on the structure of your project.

On my project, the view controller that inherit `ButtonBarPagerTabStripViewController` is child view controller. I tried to put the `self.automaticallyAdjustsScrollViewInsets = false` on there but still nothing. then I put the code on the initial view controller, the issue is solved.

**Comment by novalagung** [comment]
In case anyone still got this issue. I managed to solve it by disabling the "Adjust Scroll View Insets" on the **INITIAL VIEW CONTROLLER** (it's not always the one that inherit `ButtonBarPagerTabStripViewController`, it could be different).

On my project, the view controller that inherit `ButtonBarPagerTabStripViewController` is child view controller. I tried to put the `self.automaticallyAdjustsScrollViewInsets = false` on there but still nothing. then I put the code on the initial vc, the issue is solved.
