### ISSUE TITLE
How to have icons in Bars in version 3

### ISSUE THREAD

**Issue by aferrerb** [xmartlabs/XLPagerTabStrip#207]
Hi, I am using version 3 because my project is not using SWIFT. I wanted to know if in version 3.00 the following is possible:
1. The title changes as user swipes. At the moment it shows the project title.
2. Instead of the words shown on the bar, I want to have icons.

Is the above possible?
Thanks very much!

**Comment by fedeojeda95** [comment]
Hi @aferrerb 

Yes, you can have icons instead of word in the tab. There's a `init` for the `IndicatorInfo` that receives a image. Just create the `IndicatorInfo` in the method `func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo` with the mentioned `init` and it will show the image.

Regarding the first point mentioned, I could not understand which title you were talking about. Is it the `UINavigationController` title or another one?

Hope this helps! Regards,

**Comment by aferrerb** [comment]
hi @fedeojeda95 Thank you! Sorry was busy doing another project, and now doing this one.
Your suggestion worked. Thank you and sorry for taking time to reply. I love this library!!
