### ISSUE TITLE
Black screen below tab bar on left or right scroll

### ISSUE THREAD

**Issue by kishykumar** [xmartlabs/XLPagerTabStrip#210]
I am seeing a black screen below the tab bar when I scroll  to the left or right beyond the visible portion of screen. 

In other words, (because it's hard to explain this) I keep on scrolling left and I see this black screen below tabBar. 

Any idea what's happening? 

![img_0031](https://cloud.githubusercontent.com/assets/1509180/17830364/36954536-667e-11e6-838a-11c65078fa24.png)

**Comment by luizbim** [comment]
Same case here. To work properly I manually set background color in master ViewController wich extends ButtonBarPagerTabStripViewController.

**Comment by fedeojeda95** [comment]
Hi @kishykumar 

The problem is that when the `buttonBarView` is scrolled to its limits, the background is shown. This means that the black color you are seeing is the `backgroundColor` of the view in the container viewController (the class that implements `ButtonBarPagerTabStripViewController`). 

Setting the background color of the view in the viewController to the same background color of the tabs should do the trick.

Hope it helps! Regards,
