### ISSUE TITLE
No containerView in Storyboard - Xcode 8

### ISSUE THREAD

**Issue by jwelton** [xmartlabs/XLPagerTabStrip#244]
Here is my setup:
- Xcode Version 8.0 (8A218a)
- Installed via Carthage from current `master` (d12b4fa6c51f091deb06dd4ba9eaec66d6102fbb)
- Swift 3

I feel like this is a really simple problem. I have the following code:

``` swift
import Foundation
import XLPagerTabStrip

class MyContainerController: ButtonBarPagerTabStripViewController {

}
```

In the Storyboard, I have dragged in a `UIViewController` and set its class property to `MyContainerController`. However, I cannot see any additional `@IBOutlets` for me to connect anything too? No `containerView` or any other outlets? Am I missing something here?

In addition to the above code, I've also tried copying the `SpotifyExampleViewController` given in the example documentation and that doesn't seem to allow access to it either.

**Edit**
I believe this to be Carthage specific issue. I've just installed via Cocoapods and the outlets appear fine.

**Comment by Shannon-Yang** [comment]
Because with Carthage integration can not be changed，You can drag an own containerView by Storyboard，Naming Do not repeat XLPagerTabStrip of containerView，For example: xxxcontainerView，Then before viewDidLoad()，You can do this:  self.containerView =  self.xxxcontainerView，At least I do so there is no problem

**Comment by santiagofm** [comment]
Hey guys! This issue seems to be resolved now! All outlets appear in the `Connections Inspector` and are *connectable*.
In the case of the `buttonBarView`, you have to set the class of the view to `ButtonBarView` to be able to connect it **and** the Module to `XLPagerTabStrip` to avoid the app crashing because of the class missing.

Cheers
