### ISSUE TITLE
Can we use the same childViewcontroller  for different items on buttonBarView showing dynamic data depending on response?

### ISSUE THREAD

**Issue by Gerald93** [xmartlabs/XLPagerTabStrip#267]
Before submitting issues ...

- Make sure you are using XLPagerTabStrip [latest release](https://github.com/xmartlabs/XLPagerTabStrip/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/XLPagerTabStrip/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: XLPagerTabStrip, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as example code that you think it would be useful to understand, reproduce and solve the problem.

**Comment by htarwara6245** [comment]
http://stackoverflow.com/q/42338139/3378606

Same here

**Comment by santiagofm** [comment]
For the children i don't think you can use the *same* instance of a `UIViewController` because the framework would be possibly trying to transition from/to the same child `UIViewController` on a swipe. It would be better to have multiple instances of the same `UIViewController` configured depending on the response that you talk about.

Cheers
