### ISSUE TITLE
updateIndicator function bug?

### ISSUE THREAD

**Issue by AdAvAn** [xmartlabs/XLPagerTabStrip#276]
```swift  
      override  func updateIndicator(for viewController: PagerTabStripViewController, fromIndex: Int, toIndex: Int, withProgressPercentage progressPercentage: CGFloat, indexWasChanged: Bool) {
    
        super.updateIndicator(for: viewController, fromIndex: fromIndex, toIndex: toIndex, withProgressPercentage: progressPercentage, indexWasChanged: indexWasChanged)
            
            if indexWasChanged && toIndex > -1 && toIndex < viewControllers.count {
                
             
                print("f\(fromIndex) t\(toIndex) i\(viewController.pageFor(virtualPage: toIndex))")
              
              
                    let child = viewControllers[toIndex] as! IndicatorInfoProvider
           
                    UIView.performWithoutAnimation({ [weak self] () -> Void in
                        guard let me = self else { return }
                        me.categoryName.text =  child.indicatorInfo(for: me).title
                        

                    })
                }
        
        }

```

If I make the transition to a single controller forward or backward, the method works correctly and I get the controller ID.

If I move more than one controller is the method works off twice, I get the ID of the previous originally id then the current controller.

**What I see in the console:**

I transition from 0 to 1 controller
f0 t1 i1
I transition from 1 to 2 controller
f1 t2 i2
I transition from 2 to 3 controller
f2 t3 i3

I transition from 3 to 6 controller
f4 t5 i5
f5 t6 i6

I need ID just end controller - 6 is not necessary - 5.
**How do I get id 6, without the 5 th?**

Thanks for the help

**Comment by IVANKRUPSKI** [comment]
I guess I have similar problem, and I tested it on the YoutubeExample.

So the problem is the following:

1. When I slide the childView itself (not the ButtonBarItem) everything works fine, because I slide from the current childView to either exactly next one (to the right) or exactly previous one (to the left), without any intermediate childView(s).

2. !!! But, when, for moving from/to childViews, I tap ButtonBarItem (icos/ labels on the top), there could be a situation when I move from childView 1 to childView 6 directly, skipping childViews 2,3,4, and 5.

**And here is the problem:** Somehow when I go from childView 1 to childView 6, childView 5 is returned for a moment, and, for example, category name (in the YoutubeExampe these are HOME, TRENDING and ACCOUNT) changed twice.

I added gif file to show the effect, watch category name.


![gifvideo](https://cloud.githubusercontent.com/assets/16180201/20946814/a6b62018-bc0c-11e6-9b15-a63fa46755c1.gif)

**Comment by mtnbarreto** [comment]
I would not say that this is an issue. The propose of this method is to update the indicator and the indicator goes from the `from` to the `to` index. Depending on how the containerView (UIScrollView) delegate methods are invoked by UIKit, it can pass through intermediate indexes.

You may want to check `open func moveToViewController(at index: Int, animated: Bool = true) ` that lets you know when the user tap on a Button Bar item.

**Comment by Etheriq** [comment]
how I know what button bar item index user was tapped?
