### ISSUE TITLE
There will be wide space under buttonBarView when swipe to switch view controllers

### ISSUE THREAD

**Issue by imadeit** [xmartlabs/XLPagerTabStrip#290]
Hi,

Recently, I updated to Swift 3 and upgrading to XLPagerTabStrip 6.0.0.
I am using Xcode 8 and Swift 3.0.2 based codebase.
And I found if I swipe to switch view controllers from left to right or from right to left, there was wide space under buttonBarView, like the red box in image below indicated,
however, clicking items in buttonBarView would not cause such phenomenon.
I tried to trace the containerView's content size,
the "y" offset changed to -64 when using swipe, which is expected to be 0, so I think this would be the reason why there was wide space under buttonBarView.
Then I wonder how this issue can be solved.
Can someone be helpful, and I will be grateful.

Thanks!

<img width="526" alt="iphone7plus" src="https://cloud.githubusercontent.com/assets/4738872/21422714/4dfa12e6-c87c-11e6-99e2-7c452824aca9.png">

**Comment by FerFrassia** [comment]
Same problem here

**Comment by n1rocket** [comment]
Same problem too, i can't solve it.

**Comment by mervekeles** [comment]
same problem, any solutions?

**Comment by FerFrassia** [comment]
I ended up removing the framework and creating my own slide. It went great, if you guys are interested I'll show you

**Comment by mervekeles** [comment]
Would like to take a look at it. Thanks!

-Merve

**Comment by FerFrassia** [comment]
I just coded a sample:
https://github.com/FerFrassia/iOS/tree/master/PagerSample

Cheers.

**Comment by mtnbarreto** [comment]
Guys, Are you using Interface builder to create the pager controller?

**Comment by FerFrassia** [comment]
hey @mtnbarreto!

Yeah, I was using it. 
Could it have been a recent change to Swift 3 that made the bug?

**Comment by jettandres** [comment]
+1 for this

Hi @mtnbarreto 
yep, I'm also using interface builder to create the pager controller

**Comment by ryan-w** [comment]
Setting `self.automaticallyAdjustsScrollViewInsets = false` in the `viewDidLoad` of the ButtonBarPagerTabStripViewController derived class appears to have resolved this issue for me.

**Comment by pavankumarchalla** [comment]
no luck, after adding self.automaticallyAdjustsScrollViewInsets = false in the viewDidLoad of ButtonBarPagerTabStripViewController derived class.
Still the bug exists.

**Comment by AgapovOne** [comment]
Have the same issue. `automaticallyAdjustsScrollViewInsets` doesn't help.

**Comment by fedeojeda95** [comment]
Hi! 

Are you using a `UITableViewController` as a `childViewController`? This issue seems to happen in this case.

To fix this issue, you should be setting `automaticallyAdjustsScrollViewInsets = false` and also having as `childViewControllers` only `UIViewControllers` with a `UITableViewController` inside, instead of `UITableViewController`.

Hope it helps! Regards,

**Comment by AgapovOne** [comment]
Hi, @fedeojeda95 

I am using `[UIViewController]` array with a collection view inside. Initializing them with storyboards.
The issue is happening on all of them except for the first one.

**Comment by fedeojeda95** [comment]
Hi @AgapovOne 

I tried reproducing your issue by creating a `UIViewController` and with interface builder I added a `UICollectionView` to it, add some constraints and set the outlet. I seemed to have no issue with the top space, it was just next to the top. Could you further tell what's the problem and maybe post some code? 

Cheers

**Comment by AgapovOne** [comment]
@fedeojeda95 
I have debugged this behavior.
Used default `ButtonBarPagerTabStripViewController`. The issue happened was with layout margins of `containerView: UIScrollView`'s `contentView`. It had edge insets with 8 points on each side.

Fixed it by adding this:
```
// file: PagerTabStripViewController.swift
// method: updateContent()
open func updateContent() {
...
                    childController.view.autoresizingMask = [.flexibleHeight, .flexibleWidth]
                    childController.view.layoutMargins = .zero // added this line.
                    containerView.addSubview(childController.view)
...
```

Not sure if it won't break other behavior with library, but it helped in my current situation.

_Also, that's strange, but this issue seems to happen on 2 modules of 3. The last one works great. As I can see, it happens only when collection view has space to scroll up&down. It doesn't happen if collection view has 1 item that can't be scrolled._

This is the issue: (top white space below button bar)
![screen shot 2017-05-16 at 10 54 47](https://cloud.githubusercontent.com/assets/4246455/26091665/1e058bf8-3a26-11e7-9490-af7e58f84a5f.png)
