### ISSUE TITLE
Change starting position of buttons?

### ISSUE THREAD

**Issue by larrynatalicio** [xmartlabs/XLPagerTabStrip#292]
Is there any way to change the position of the Button Bar View to match this picture?

<img width="378" alt="positions" src="https://cloud.githubusercontent.com/assets/11169517/21558541/b1cead6c-ce09-11e6-8ccf-c9c4844fcee8.png">

Notice how the text "Daily Top 10" is not all the way to the left to begin with even though that is the first `View Controller`. It starts off centered. Can I control this position as well with this library?

**Comment by fedeojeda95** [comment]
Hi @larrynatalicio 

In order to achieve this, if you are using the `ButtonBarPagerTabStripViewController`, there's a property inside `Style` struct inside `ButtonBarPagerTabStripSettings` called `buttonBarLeftContentInset`. This float value represents the left inset for the first element in the button bar. 

Remember to set it before the `super.viewDidLoad()` is called in your `viewDidLoad`.

`
class ButtonBarExampleViewController: ButtonBarPagerTabStripViewController {

    override func viewDidLoad() {
        settings.style.buttonBarLeftContentInset = //inset goes here
        super.viewDidLoad()
   }

`
Hope it helps! Regards,

**Comment by fedeojeda95** [comment]
I'm closing this due to the lack of an answer, but feel free to open more issues if you have further questions!

**Comment by ravinleague** [comment]
@fedeojeda95 I'd like to put the strip somewhere in the middle of the screen.. how do i do that ?
