### ISSUE TITLE
Crash when supplying image to IndicatorInfo

### ISSUE THREAD

**Issue by eman6576** [xmartlabs/XLPagerTabStrip#295]
- Environment: XLPagerTabStrip, Xcode 8.2.1, iOS 9.3
- Xcode console output of stack trace: fatal error: unexpectedly found nil while unwrapping an Optional value
- When implementing protocol `IndicatorInfoProvider` and returning an instance of `IndicatorInfo` with an image, a crash occurs when trying set the image to the the imageview of the buttonbarcell.
Here is a screenshot of where the crash occurs:
<img width="921" alt="screen shot 2017-01-13 at 3 04 59 am" src="https://cloud.githubusercontent.com/assets/16155920/21922533/1ed8065e-d93d-11e6-9b09-2170f10292b6.png">

Here is how I implemented the `IndicatorInfoProvider` protocol:
<img width="926" alt="screen shot 2017-01-13 at 3 06 30 am" src="https://cloud.githubusercontent.com/assets/16155920/21922565/4f83ee94-d93d-11e6-80e4-dba7268e5624.png">

Thanks :]

**Comment by amannayak0007** [comment]
Same Issue with me.
Please Help.

**Comment by Shaqman27** [comment]
Look at ButtonBarViewCell.xib:
It has an outlet for an imageView, but no actual UIImageView was added to the cell.

**Comment by amannayak0007** [comment]
Thanks!
Adding imageView in the cell and connecting the outlet worked for me.

**Comment by Shaqman27** [comment]
There are 2 modes, "text only" mode, and "text + image" mode.
If you only need one of those modes, then you're fine, but if you need both modes in the same app, like me, you have to play around with the constraints to support positioning in each mode.

**Comment by mtnbarreto** [comment]
Take a look how `YoutubeExampleViewController` is created. Basically it extends from aseButtonBarPagerTabStripViewController<YoutubeIconCell> which is a generic view controller that allows to specify the bar menu collection cell, in this case `YoutubeIconCell`. 

I didn't document this because it's hard to connect interface builder view controller with a generic view controller class since the vc type is not suggested in the xcode IB editor.

You have to let the library knows how to load the bar item cell by specifying  `buttonBarItemSpec` property. 

```swift
buttonBarItemSpec = ButtonBarItemSpec.nibFile(nibName: "YoutubeIconCell", bundle: Bundle(for: YoutubeIconCell.self), width: { (cell: IndicatorInfo) -> CGFloat in
                return 55.0
        })
```

we need also to set up the cell by overriding: 

```
    override func configure(cell: YoutubeIconCell, for indicatorInfo: IndicatorInfo) {
        cell.iconImage.image = indicatorInfo.image?.withRenderingMode(.alwaysTemplate)
    }
```

> Notice that  the first parameter type is the base view controller generic type.

the rest is pretty much the same. 


Hope it's helps

**Comment by zhanswift** [comment]
How to do programmatically?
