### ISSUE TITLE
Segue is not working

### ISSUE THREAD

**Issue by MHX792** [xmartlabs/XLPagerTabStrip#316]
Performing a segue from `NavButtonBarExampleViewController` results in this:

![screen shot 2017-02-10 at 23 57 35](https://cloud.githubusercontent.com/assets/12123471/22847365/c9056840-efec-11e6-8fa9-0a854372ca0f.png)

How to fix this?

**Comment by santiagofm** [comment]
Hey @MHX792 !

That happens because the `buttonBarView` is added as a subview of the `navigationBar`, and the `navigationBar` itself is a subview of the `navigationController` rather the `visibleViewController` and so it persists after you push another viewController.
As a workaround you can show/hide the `buttonBarView` in the `viewWillAppear` & `viewWillDisappear` respectively, like so:

```swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
        
    buttonBarView.isHidden = false
}
    
override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
        
    buttonBarView.isHidden = true
}
```

Hope this helps you!
Cheers

**Comment by santiagofm** [comment]
Closing due to lack of response.

**Comment by MHX792** [comment]
Helped. Thanks. ;) But there is a little bug: when you go back by swiping your thumb from the left edge of the screen (instead of pressing the back button) and in the middle of swiping you decide for not going back, then the `navigationBar` of the sub view and the `buttonBarView` of the parent view will overlap.
