### ISSUE TITLE
moveToViewController not working at index 0

### ISSUE THREAD

**Issue by MahmoudTarek** [xmartlabs/XLPagerTabStrip#318]
Hello, 
I'm implementing something like news feed, where the newsfeed controller is at index 0 in the segmented view controller.

In viewWillAppear that will get called every time I open the segmented view controller from the tab bar (I'm using Tab Bar controller, segmented view controller is one of it) I'm checking if I have any updates so I move programmatically to the newsfeed view controller. 

moveToViewController works fine if I try to move at any index apart from 0 which is my target.

**Comment by MahmoudTarek** [comment]
Updates, moving the code to viewDidAppear made it work but it freezes the UI..

**Comment by samirthebti** [comment]
@MahmoudTarek can you put how you implement the moveToviewController function ?

**Comment by pepejeria** [comment]
I am also getting an UI freeze when calling either moveToViewController or the moveTo method. Anybody knows what could be causing this?

**Comment by santiagofm** [comment]
hey guys ! 

This issue is somewhat related to #357. 
The `moveToViewController(at:)` function checks that `isViewLoaded && view.window != nil` is `true` in order to perform the move. But you are calling the function in  `viewWillAppear(...)` and so `view.window != nil` fails because the view hasn't been added to a view hierarchy quite yet.
I proposed a couple of changes that will fix this issue in #367.

Thanks
