### ISSUE TITLE
Unable to pass data 

### ISSUE THREAD

**Issue by IronCoderXYZ** [xmartlabs/XLPagerTabStrip#324]
I am running the newest version of iOS & XCODE

I know how to pass data from one VC to the next using performSegue, however this situation is a little different.

CalendarVC - Holds the Data

transfers to calendarDetailsVC when a date is selected from the calendar

CalendarDetailsVC - Holds XLPagerTabStrip

CalendarDetailsBSVC - Needs to display variables form CalendarVC

When I try: (in CalendarVC since it has the data)

override func prepare(for segue: UIStoryboardSegue, sender: Any?) {

        let destination = segue.destination as! CalendarDetailsBSVC
        let test = "SDFDSFDSF"

        destination.test = test
    }
I have a "var test: String?" variable in my CalendarDetailsBSVC but the program crashes with:

Could not cast value of type 'appName.CalendarDetailsVC' (0x10152e648) to 'appName.CalendarDetailsBSVC' (0x10152eba8).
I have also tried accessing the variable directly from CalendarDetailBSVC, but no luck since the variable lives inside another class' function and thus I can't access it (it needs to be modified there)

How can I accomplish transferring this data?

Thank you

**Comment by fedeojeda95** [comment]
Hi @IronCoderXYZ 

The problem is that the destination view controller in the segue is the `CalendarDetailsVC` actually, not the `CalendarDetailsBSVC`. The `CalendarDetailsBSVC` will be one of the tabs in the container view controller. 

In order to pass data to one of the tabs, you should pass it first to the container view controller, in this case, to the `CalendarDetailsVC`. Afterwards, when you implement the method `func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController]` in the `CalendarDetailsVC`, you should create the `CalendarDetailsBSVC` and set the mentioned data to it. 

This solution makes the assumption that the `CalendarDetailsVC` is the `PagerTabStripDataSource` of the `PagerTabStripViewController`. If you are using a `ButtonBarPagerTabStripViewController` for example, this is done out of the box. 

Hope it helps! Let us know if this solves the problem. 

Best regards,

**Comment by rodtaborda** [comment]
How should I do using ButtonBarPagerTabStripViewController?

ViewController A sends a string X to ViewController B (ButtonBarPagerTabStripViewController).

ViewController B has child_1 and child_2.

I need to use the string X in both children.

Now I can't receive string X in child_1 or child_2.

**Comment by fedeojeda95** [comment]
Hi @rodtaborda 

As it was mentioned, in `ViewController B` you have to implement the method `func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController]`, which is the method that tells returns the child view controllers.

Inside the implementation of this method is where you create both `child_1 ` and `child_2`. When you create both of them, you can set the controller the string `X` as a property of each of them. 

Hope it helps! Regards,

**Comment by nasznjoka** [comment]
I have a case exactly like that one above and it works but, the UIStoryBoard scene have a navigation controller that the segue points to and this causes data not to be transferred to the base controller.

ViewController A sends a string X to ViewController B (ButtonBarPagerTabStripViewController).

ViewController B has child_1 and child_2.

I need to use the string X in both children.

From the UIStoryBoard I also have navigation controller before ViewController B so when I set the segue to the navigation controller the String X is nil and also when I set the segue straight to ViewController B's Scene the String is good but there is no navigation Bar. How can I do this?
<img width="476" alt="screen shot 2017-10-20 at 04 54 05" src="https://user-images.githubusercontent.com/3130364/31801724-c70d3348-b552-11e7-8158-0ac1d37a184b.png">

So From the screenshot the segues pointing directly to the base are fine but the one pointing to the navigation controller is nil but shows the view correctly while the other ones only shows tabs
