### ISSUE TITLE
Argument labels '(style:)' do not match any available overloads

### ISSUE THREAD

**Issue by zhanswift** [xmartlabs/XLPagerTabStrip#333]
Argument labels '(style:)' do not match any available overloads

```swift
class HomeCollectionViewController: UICollectionViewController, IndicatorInfoProvider {
    init(style: UITableViewStyle, itemInfo: IndicatorInfo) {
        self.itemInfo = itemInfo
        super.init(style: style)
    }
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by m-revetria** [comment]
Hi @zhanswift, 

I'm not sure how this is related to `XLPagerTabString` library. It looks like a simple compilation error due to `UICollectionViewController` doesn't expose an initializer with signature `init(style: UITableViewStyle)`. Maybe you should have used `UITableViewController` instead of `UICollectionViewController`

**Comment by m-revetria** [comment]
Please do not use the issue tracker for personal support requests. Stack Overflow is a better place for that where a wider community can help you!
