### ISSUE TITLE
Cancel Moving

### ISSUE THREAD

**Issue by carloscrono** [xmartlabs/XLPagerTabStrip#341]
It's possible to cancel scrolling or moving to a secondary controller?

**Comment by fedeojeda95** [comment]
Hi @carloscrono 

Currently there is no way to disable the horizontal scrolling. None of the options of navigation (the top navigation or the drag in the contentView) can be disabled. 

Nevertheless, you could achieve this manually if you really need to. One of the options could be by disabling the using interaction for the view that represents the top navigation and to override the scrollView delegate methods necessary to provide your implementation that prevents the navigation. For example, if you are using a ButtonBarPagerTabStripViewController, you could do the following:

`
class ButtonBarExampleViewController: ButtonBarPagerTabStripViewController {
    
    //This var indicate if the navigation is enabled
    //When it is set, be enable or disable the top navigation element
    var shouldScroll = true {
        didSet {
            buttonBarView.isUserInteractionEnabled = shouldScroll
        }
    }

    //If shouldScroll is true, we call the parent class implementation since it has already 
    //implemented the navigation. If not, we make the scrollView to maintain fixed
    override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if shouldScroll {
            super.scrollViewDidEndScrollingAnimation(scrollView)
        } else {
            scrollView.contentOffset.x = 0.0
        }
    }

    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
    //Here goes the controllers setup
   }

}
`

This same logic can be applied for every other controller, but instead of disabling the `buttonBarView`, you should disable the corresponding navigation element.  

Hope it helps! Regards,

**Comment by carloscrono** [comment]
Thanks.

I have already disabled buttonBarView scrolling by adding 

`override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
    //Nothing here
  }`

And the containerView scrolling:

`static var container = super.containerView
Controller.container?.isScrollEnabled = false
`

I need to validate my TableView before user can Scroll.

Thanks for your tips, I'll try to make it better with that.
