### ISSUE TITLE
how can i add childviewcontroller  programmatically

### ISSUE THREAD

**Issue by freddy2013** [xmartlabs/XLPagerTabStrip#349]

**Comment by m-revetria** [comment]
Hi @freddy2013,

In order to add a new child view controller you need to refresh the entire `PagerTabStripController`. In order to do that, you have to call to `PagerTabStripController.reloadPagerTabStripView` which will call your implementation of `func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController]`.

Take into account that you might avoid re-creating all child controllers each time `viewControllers(for:) -> [UIViewController]` is called.

Regards
