### ISSUE TITLE
Refresh Tableview in childcontainer

### ISSUE THREAD

**Issue by aferrerb** [xmartlabs/XLPagerTabStrip#351]
Hello, is it possible to refresh the tableview of a child container? I am using pulltorefresh, I then call tableview refresh data, but the tableview does not actually get refreshed. 
Is it possible to refresh the tableview inside a child container?
Thanks

**Comment by m-revetria** [comment]
Hi @aferrerb,

Refreshing a child controller's tableView is not something that `XLPagerTabString` can natively supported because it doesn't restrict child view controllers to have a table view. 

As I don't know how your code looks like, I guess that when the pull-to-refresh event is fired you can get the list of child controllers by accessing to the `childControllers` property from your `PagerTabStripViewController` and then call to refresh the table for each of them.

I would define a protocol or a base class for the child view controllers in order to safely call to refresh their table.

If you provide us with more information we might be more helpful :)

Regards
