### ISSUE TITLE
Cannot see the titles using XLButtonBarPagerTabStripViewController

### ISSUE THREAD

**Issue by mnhsoftskills** [xmartlabs/XLPagerTabStrip#36]
Using XLButtonBarPagerTabStripViewController there are no titles even if I use titleForPagerTabStripViewController delegate method in my childviewcontroller!

Childviewcontroller conforms to <XLPagerTabStripChildItem>
# pragma mark - XLPagerTabStripChildItem Delegate
- (NSString *)titleForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController {
  return @"TITLE";
  }

And in my container class that is the Subclass of XLButtonBarPagerTabStripViewController I have to write:

//If I do not write below line app crashes! Already raised an issue on this earlier!
    [self.buttonBarView registerClass:[XLButtonBarViewCell class] forCellWithReuseIdentifier:@"Cell"];

//As per the Demo
    [self.buttonBarView setBackgroundColor:[UIColor greenColor]];
    [self.buttonBarView.selectedBar setBackgroundColor:RGBCOLOR(52.0, 166.0, 212.0, 1.0)];

//And in below method  I have 4 controllers showing as childcontrollers. 

-(NSArray *)childViewControllersForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController
{
 // .. Code to return multiple viewcontrollers ..
}

**Comment by pablomarti** [comment]
Hi, is there a solution for this issue?

**Comment by OliverPearmain** [comment]
Can you not put a breakpoint with-in the XLPagerTabStrip code where it calls titleForPagerTabStripViewController and see whats happening?

**Comment by mnhsoftskills** [comment]
Want to hire our development team?? Let's discuss 

Sent from my iPhone

Vipul SHAH

**Comment by wanchopeblanco** [comment]
Im having the same problem with TwitterPager when using it in a navigation controller.

**Comment by laiying** [comment]
@mnhsoftskills hi,mnhsoftskills,I have same problem with using XLButtonBarPagerTabStripViewController,did you solve?

**Comment by wanchopeblanco** [comment]
In my case the title shows when showing a modal view and then dismissing it or when i try to pull the view from the left edge to go back but returning back to the view.

**Comment by eduardobc** [comment]
I´m having the same problem using XLButtonBarPagerTabStripViewController.
I have been to tried differents ways but I have not success.
I´m using 'XLPagerTabStripMiniExample' as example

**Comment by mtnbarreto** [comment]
I really appreciate if someone can upload a project reproducing the issue so i can look into it.

**Comment by quiet324** [comment]
I have same problem.

**Comment by quiet324** [comment]
[Uploading XLPagerTabStrip.zip…]()

**Comment by akiramonster** [comment]
please help , this problem drives me crazy :(

**Comment by artekr** [comment]
I was also struggling with this issue with two whole night!!! And I finally find the difference between the example project with my own. The problem is on the **NavigationBar**.
Before modifying anything, the content size of the Navigation Controller, the height is equal to 600:
![screen shot 2016-05-05 at 12 22 55 am](https://cloud.githubusercontent.com/assets/2516988/15036053/33982f62-1258-11e6-931c-7f1b00bfd731.png)

What you need to do is go to the storyboard, select NavigationBar:
![screen shot 2016-05-05 at 12 23 26 am](https://cloud.githubusercontent.com/assets/2516988/15036071/59095226-1258-11e6-9b94-d9894ecedfbd.png)

On the left Attributes Inspector, uncheck Translucent box:
![screen shot 2016-05-05 at 12 23 36 am](https://cloud.githubusercontent.com/assets/2516988/15036089/7ee6fd90-1258-11e6-8ad7-125221f037b3.png)

Check the content size again, the height is 536, which is minus the nav bar height and status bar height:
![screen shot 2016-05-05 at 12 23 45 am](https://cloud.githubusercontent.com/assets/2516988/15036098/9d0effca-1258-11e6-9f27-e9c63476cf17.png)

Now when you run the project, you should see the title of the tab of each child view controller.
This step should either be fixed or needs to be specified in the Usage section in this repository.

And when you setup the buttonBarView, make sure you drag the UICollectionView and delete the UIcollectionViewCell in it, I suggest download the Example project and take it look how it configures in the storyboard.

**Comment by ElectroBuddha** [comment]
Thanx @artekr for the solution. But this is too bad, because I need translucent NavigationBar :(
