### ISSUE TITLE
Remove and add tab buttons

### ISSUE THREAD

**Issue by FaridHaddad** [xmartlabs/XLPagerTabStrip#363]
Hello,

I have a search bar in my navigation bar (like the instagram app) and i need to show the buttons tabs only when the user begins editing the search bar. If the search bar is not being edited, i must remove everything related to the tabs and show some tableview. How can i do that ? i can't figure out a way ..

Thanks

**Comment by santiagofm** [comment]
Hi @FaridHaddad, 

I suppose you are using a `UISearchController` to manage the search in which case you can set your vc as it's delegate and implement `willPresentSearchController` & `willDismissSearchController` where you could show/hide the `ButtonBarView`.

Please let me know if I can be of any further help

Thanks!

**Comment by santiagofm** [comment]
Closing due to lack of response.

**Comment by burgercode** [comment]
Hi!

I'm exactly in this situation. As @santiagofm mentioned, I tried to hide the `ButtonBarView` with `buttonBarView.isHidden = true` in `willPresentSearchController` but the thing is that the `searchResultsController` of the `UISearchController` doesn't stick to the top of the screen. There is a white space between the search bar and the `searchResultsController` that is exactly the size of the `ButtonBarView `. Any idea on how to solve this?

```
private var searchController: UISearchController!
private lazy var textSearchVC = factory.makeTextSearchViewController(delegate: self)

override func viewDidLoad() {
    ...
    super.viewDidLoad()

    searchController = UISearchController(searchResultsController: textSearchVC)
    }
```

```
func willPresentSearchController(_ searchController: UISearchController) {
    containerView.isHidden = true
    buttonBarView.isHidden = true
}
```
Margin before the start of the list:
![IMG_6113](https://user-images.githubusercontent.com/26303997/65685791-1c23c080-e063-11e9-8323-12a071153d19.PNG)

When scrolling we can see a white box:
![IMG_6114](https://user-images.githubusercontent.com/26303997/65685793-1c23c080-e063-11e9-99db-d846403241fa.PNG)

I guess it's because `searchResultsController` is instantiated while the `ButtonBarView ` is still present and that it isn't resized correctly but I have no idea how to solve it.
