### ISSUE TITLE
viewWillTransition method not firing for all tabs

### ISSUE THREAD

**Issue by viral-etymon** [xmartlabs/XLPagerTabStrip#387]
XLPagerTabStrip: 7.0.0
Xcode:  8.3.2
iOS: 10.3.2

I have implemented XLPagerTabStrip and it is working fine. I have included 5 tabs and each containing collection view. And on device rotation I have to make some cell resizing related code. To detect device rotation I am using **_viewWillTransition_** method.

Issue I am facing is only parent VC (containing all tabs) and current selected tab (selected VC) getting **_viewWillTransition_** method other inactive tabs are not getting this method.

It means only selected tab will get **_viewWillTransition_** method and other is not getting. I think all tab should get this event, and is there any way to achieve this?

**Comment by fedeojeda95** [comment]
Hi @viral-etymon 

I'm not sure what this can be about, but it may be due to the fact that the controller are not being shown in the screen when the view transition.

As a workaround, what do you think about having a method inside each of your child view controllers that receives the same parameters as the `viewWillTransition`. With this method, whenever the `viewWillTransition` is called in the parent VC, you can iterate through the child VCs and call this method. You can even put this method inside a protocol and make all your child VCs conform it. What do you think about that? 

Hope it helps! Regards,

**Comment by viral-etymon** [comment]
Yes you are right that I can create some protocol and child VCs can conform it, I keep this as last option. Any ways thank you for your time and reply. :-)
