### ISSUE TITLE
fix bug:the TableView scroll with uncorrect position:Y

### ISSUE THREAD

**Issue by o0starshine0o** [xmartlabs/XLPagerTabStrip#69]
I used XLPagerTabStrip in IB:
![image](https://cloud.githubusercontent.com/assets/6480059/9538070/ef44fbc4-4d72-11e5-946d-18c783b86ae7.png)
When I touched XLButtonBarView in HaveFinishedViewController,the TableView scroll with incorrect position Y.I find the bug in XLPagerTabStripViewController.m:

line 157,160,288,395:[self.containerView setContentOffset:CGPointMake([self pageOffsetForChildIndex:index], 0) animated:YES];

and I fixed this bug by modify these line : 

line 157,160,288,395: [self.containerView setContentOffset:CGPointMake([self pageOffsetForChildIndex:index], self.containerView.layer.bounds.origin.y) animated:animated];

because the Y-position isn't always 0,I use containerView's Y-position instead.

I hope this bug will be fixed in the future.

**Comment by RockyLin** [comment]
I modified the source according your solution, but it doesn't work.

**Comment by o0starshine0o** [comment]
This issue was post to fix bug: XLButtonBarView scrolling while Y position changed.
Can I review your code to find out the bug?

**Comment by mtnbarreto** [comment]
This is not directly related with the library. 
The problem occurs because in some cases (depending on how we put the views on the screen using storyboard) the navigation bar covers the contentview and view controller *Adjust Scroll View Insets* is enabled.

In this case iOS adjusts the contentoffset `y` value for the childViewController that appears during presentation, then the user swipe left right and move on to another child view controller that does't get this adjust and therefore is covered by the navigation bar. 

I've fixed the issue adding constraints to the contentView to prevent the contentView to be covered by the navigation bar.

Alternatively if all the childViewControllers view appear covered by the navbar or you intentionally want to have the child views covered by the nav bar you can use this code:

```obj-c
- (void)viewDidLoad {
    [super viewDidLoad];
    ......
    ....
    ..
    UIEdgeInsets inset = self.containerView.contentInset;
    inset.top = 64;
    self.containerView.contentInset = inset;
   ..
```

**Comment by mrigdon** [comment]
I think I'm still having this problem
